### ISSUE TITLE
Documentation unavailable

### ISSUE THREAD

**Issue by aaronkjones** [birlorg/bitwarden-cli#12]
I am unable to access the installation documentation website (can access the html in the repo).
You may want to consider using github.io or other static site web host.

```ping fossil.birl.ca
PING fossil.birl.ca (138.68.40.166): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

curl -L https://fossil.birl.ca
^C

host fossil.birl.ca
fossil.birl.ca has address 138.68.40.166```

**Comment by birlorg** [comment]
DOH. Sorry.  I thought I updated DNS, but clearly I failed miserably.

I updated DNS, once it catches up, life should be good again.

In the meantime, the doc is available here: https://github.com/birlorg/bitwarden-cli/blob/trunk/docs/source/installation.rst in readable(and source) form, since the HTML is generally annoying on Github.

**Comment by birlorg** [comment]
also it seems people still care about this code, oddly enough.

When I wrote this, the official one didn't exist. I'm curious why people are using(or wanting to use) this over the bitwarden offical CLI, since it exists now. [https://help.bitwarden.com/article/cli/]?

**Comment by birlorg** [comment]
Documentation (and the fossil.birl.ca website) is working for me now.

**Comment by aaronkjones** [comment]
Some Google search brought me here (I think). I didn't realize an official tool existed. Thanks.
